name: Cypress API Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run-cypress-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cypress run (API only)
        uses: cypress-io/github-action@v6
        with:
          start: echo "No app to start"
          command: npx cypress run
        env:
          REQRES_API_KEY: ${{ secrets.REQRES_API_KEY }}
